### ISSUE TITLE
Train fail. Error occurred when executing InitFluxLoRATraining:  Cannot copy out of meta tensor; no data! 

### ISSUE THREAD

**Issue by ultimatech-cn** [kijai/ComfyUI-FluxTrainer#6]
<img width="629" alt="1724314555665" src="https://github.com/user-attachments/assets/9aa70442-6d83-4192-b9d8-2d8262bd9072">
The first time train lora only because comfyUI is easy to use. Copy dataset to ComfyUI folder.
<img width="752" alt="1724314759057" src="https://github.com/user-attachments/assets/24155053-dce2-4a4a-9b8a-6de548b7eb3f">
Got the following errors.
>  !!! Exception during processing!!! Cannot copy out of meta     execution.py:180
>                              tensor; no data! Please use torch.nn.Module.to_empty() instead
>                              of torch.nn.Module.to() when moving module from meta to a
>                              different device.
>                     ERROR    Traceback (most recent call last):                             execution.py:181
>                                File "F:\ComfyUI_flus\ComfyUI\execution.py", line 152, in
>                              recursive_execute
>                                  output_data, output_ui = get_output_data(obj,
>                              input_data_all)

**Comment by Nebuluss** [comment]
I'm getting the same error (Comfy and all extension are updated)

Error occurred when executing InitFluxLoRATraining:

Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.

File "D:\ANEWCOMFY\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ANEWCOMFY\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ANEWCOMFY\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
process_inputs(input_dict, i)
File "D:\ANEWCOMFY\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
results.append(getattr(obj, func)(**inputs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ANEWCOMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\nodes.py", line 336, in init_training
training_loop = network_trainer.init_train(args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ANEWCOMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FluxTrainer\train_network.py", line 377, in init_train
vae.to(accelerator.device, dtype=vae_dtype)
File "D:\ANEWCOMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1173, in to
return self._apply(convert)
^^^^^^^^^^^^^^^^^^^^
File "D:\ANEWCOMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
module._apply(fn)
File "D:\ANEWCOMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
module._apply(fn)
File "D:\ANEWCOMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
module._apply(fn)
[Previous line repeated 3 more times]
File "D:\ANEWCOMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 804, in _apply
param_applied = fn(param)
^^^^^^^^^
File "D:\ANEWCOMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1166, in convert
raise NotImplementedError(

**Comment by Nebuluss** [comment]
This was because we were using the diffusers version of the VAE , switch to this VAE https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/ae.safetensors thanks Kijai for solving the issue :)

**Comment by JohnnyMustang** [comment]
> This was because we were using the diffusers version of the VAE , switch to this VAE https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/ae.safetensors thanks Kijai for solving the issue :)

I get the same error regardless even after downloading the VAE from that link.

**Comment by kijai** [comment]
> > This was because we were using the diffusers version of the VAE , switch to this VAE https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/ae.safetensors thanks Kijai for solving the issue :)
> 
> I get the same error regardless even after downloading the VAE from that link.

Similarly check that the other models are correct, the error definitely is related to them. Which ones are you trying to use?

**Comment by JohnnyJae** [comment]
> > > This was because we were using the diffusers version of the VAE , switch to this VAE https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/ae.safetensors thanks Kijai for solving the issue :)
> > 
> > 
> > I get the same error regardless even after downloading the VAE from that link.
> 
> Similarly check that the other models are correct, the error definitely is related to them. Which ones are you trying to use?

Yeah, you're right. I tried a different one and it worked (fp16). I don't remember which is which to be honest because I downloaded a few, but I first tried with the fp8 version and it didn't work. But that might've been one downloaded from civitai. Where should I download the fp8 version from?

**Comment by kijai** [comment]
> > > > This was because we were using the diffusers version of the VAE , switch to this VAE https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/ae.safetensors thanks Kijai for solving the issue :)
> > > 
> > > 
> > > I get the same error regardless even after downloading the VAE from that link.
> > 
> > Similarly check that the other models are correct, the error definitely is related to them. Which ones are you trying to use?
> 
> Yeah, you're right. I tried a different one and it worked (fp16). I don't remember which is which to be honest because I downloaded a few, but I first tried with the fp8 version and it didn't work. But that might've been one downloaded from civitai. Where should I download the fp8 version from?

https://huggingface.co/Kijai/flux-fp8/blob/main/flux1-dev-fp8.safetensors

**Comment by ultimatech-cn** [comment]
> > > > > This was because we were using the diffusers version of the VAE , switch to this VAE https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/ae.safetensors thanks Kijai for solving the issue :)
> > > > 
> > > > 
> > > > I get the same error regardless even after downloading the VAE from that link.
> > > 
> > > 
> > > Similarly check that the other models are correct, the error definitely is related to them. Which ones are you trying to use?
> > 
> > 
> > Yeah, you're right. I tried a different one and it worked (fp16). I don't remember which is which to be honest because I downloaded a few, but I first tried with the fp8 version and it didn't work. But that might've been one downloaded from civitai. Where should I download the fp8 version from?
> 
> https://huggingface.co/Kijai/flux-fp8/blob/main/flux1-dev-fp8.safetensors

Thank a lot. It works after using model you suggested.
But too much VRAM! Anyway to reducing it?
<img width="779" alt="1724415503482" src="https://github.com/user-attachments/assets/85fc1eeb-de45-4b63-9622-c6250e09aec4">

**Comment by kijai** [comment]
> > > > > > This was because we were using the diffusers version of the VAE , switch to this VAE https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/ae.safetensors thanks Kijai for solving the issue :)
> > > > > 
> > > > > 
> > > > > I get the same error regardless even after downloading the VAE from that link.
> > > > 
> > > > 
> > > > Similarly check that the other models are correct, the error definitely is related to them. Which ones are you trying to use?
> > > 
> > > 
> > > Yeah, you're right. I tried a different one and it worked (fp16). I don't remember which is which to be honest because I downloaded a few, but I first tried with the fp8 version and it didn't work. But that might've been one downloaded from civitai. Where should I download the fp8 version from?
> > 
> > 
> > https://huggingface.co/Kijai/flux-fp8/blob/main/flux1-dev-fp8.safetensors
> 
> Thank a lot. It works after using model you suggested. But too much VRAM! Anyway to reducing it? <img alt="1724415503482" width="779" src="https://private-user-images.githubusercontent.com/142652112/360923448-85fc1eeb-de45-4b63-9622-c6250e09aec4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NTM5OTgsIm5iZiI6MTcyNDQ1MzY5OCwicGF0aCI6Ii8xNDI2NTIxMTIvMzYwOTIzNDQ4LTg1ZmMxZWViLWRlNDUtNGI2My05NjIyLWM2MjUwZTA5YWVjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QyMjU0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDBjMTM2MDE3MWMxM2RiMDVmNmQ0MjI5ZmU2YzUzZWUxMTNiNGRlN2JlMjliMmE3OTZlZmUwZWE2ZGU1NzgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z98b6Nd1QkWqSw8OMpetgHiwOlubFz1Xz1q6YSuFjJY">

If you are using the default settings it shouldn't use that much. Some people have said it helps to upgrade pytorch to 2.4.0 minimum, so if you are on 2.3.x then that could be the issue.

**Comment by ultimatech-cn** [comment]
Up torch to 2.4. The VRAM usage downgrade to 17G.
